### ISSUE TITLE
Nhiệm vụ trong tuần nghỉ Tết 🤡🤡🤡

### ISSUE THREAD

**Issue by thanhthao10A12** [thanhthao10A12/Lop-10A12-Nhom-09#11]
- **Năm mới zui zẻ, hạnh phúc nha mng**🌹🌷🍀🐯🐯🐯
-  **Nhiệm zụ: cảm nhận xung quanh, trò chuyện với mọi người để có thể tìm ra được thành ngữ / tục ngữ / ca dao hoặc thơ phù hợp để diễn tả được suy nghĩ trong bài làm**

**Comment by thanhthao10A12** [comment]
alo cả nhà ới

**Comment by LeQuangThuan10a12** [comment]
hii ạ

**Comment by thanhthao10A12** [comment]
mng ơi zô thảo luận để làm bài nè @duchuypn10a12 @LeQuangThuan10a12 @TranQuocDuyTVND10A12

**Comment by thanhthao10A12** [comment]
cái bài đó thì theo tui nghĩ thì nó như này nhóm mình làm chung 1 câu nào đó xong gộp thành 1 bài hoàn chỉnh, ko thì làm 1 câu nhưng mà mỗi người 1 bài một cảm nhận khác nhau, hoặc là làm mỗi người 1 câu riêng. Mng thấy sao?

**Comment by thanhthao10A12** [comment]
còn về phần trình bày word hk1 tui làm ròi, đến hk2 này mấy friend thích đổi gió khom, để 1 bạn khác làm.
bạn nào muốn sáng tạo, trang trí, trình bày gì kh thì lên tiếng iik

**Comment by thanhthao10A12** [comment]
nổ quả giờ ròi mà anh em z đó, chơi z koi được kh :}}}
![image](https://user-images.githubusercontent.com/92030942/152634115-a61e1d52-0e94-4ef4-830c-7d6ddfff5be7.png)

**Comment by TranQuocDuyTVND10A12** [comment]
Hello mọi người sorry mém xíu tui mất tài khoản

**Comment by thanhthao10A12** [comment]
giờ mng đề xuất thử đi, làm thành ngữ / tục ngữ / ca dao nào nè

**Comment by LeQuangThuan10a12** [comment]
tuii nghĩ làm tục ngữ ii cho nó dễ á

**Comment by duchuypn10a12** [comment]
ca dao dễ hơn chứ

**Comment by thanhthao10A12** [comment]
cho câu nào ví dụ thử đi mng

**Comment by thanhthao10A12** [comment]
chủ đề cuộc sống, gia đình, xã hội....

**Comment by duchuypn10a12** [comment]
Có công mài sắt có ngày tháng năm

**Comment by thanhthao10A12** [comment]
https://images.app.goo.gl/gSj2XMc3acDTRG2Q6

**Comment by TranQuocDuyTVND10A12** [comment]
Nghèo cho sạch rách cho 5 ngàn

Cuộc đời thiệt lắm éo le
Tháng sáu là tháng mùa hè nghỉ ngơi
Mọi người vừa học vừa chơi
“Phao” mà hong có đi bơi coi chừng :))

**Comment by TranQuocDuyTVND10A12** [comment]
Dĩ dzãng dzơ dzáy dễ dzì dzấu dziếm du dương di dời diện dzô dziên

**Comment by TranQuocDuyTVND10A12** [comment]
Sóng bắt đầu từ gió
Gió bắt đầu từ mưa
Lực đẩy Ác-si-mét
Thuyền đã nổi lên chưa?

**Comment by TranQuocDuyTVND10A12** [comment]
Giỡn dzui ^_^

**Comment by thanhthao10A12** [comment]
![image](https://user-images.githubusercontent.com/92030942/155846705-0ab64411-1b93-4d6a-8061-7adeefe60fed.png)

**Comment by thanhthao10A12** [comment]
Thương người như thể thương thân nhe :}}}

**Comment by thanhthao10A12** [comment]
@duchuypn10a12 trang trí, thiết kế word nha :}}}

**Comment by duchuypn10a12** [comment]
> @duchuypn10a12 trang trí, thiết kế word nha :}}}

Chắc đựt

**Comment by thanhthao10A12** [comment]
phân công như sau: 
- phần nội dung: Thuận, Duy, Vỹ
- làm word: Thảo, Huy

**Comment by thanhthao10A12** [comment]
1) Mở bài 
2) Thân bài:
a. Ý nghĩa câu tục ngữ
b. Biểu hiện của tình thương người như thể thương thân
c. giải thích: Vì sao phải yêu thương người khác như bản thân mình ....
d. Bài học 
3) Kết bài
------------------------------------------
này là dàn ý câu tục ngữ
mấy bạn soạn nội dung mỗi người chọn 2 ý để làm nha

**Comment by LeQuangThuan10a12** [comment]
tui làm phần bài học dới kết bài nhee mng ơi :33

**Comment by PhanChiVy** [comment]
tui làm phần mở bài với ý nghĩa leh mng

**Comment by TranQuocDuyTVND10A12** [comment]
- Thương người nghĩa là chúng ta phải luôn luôn mở rộng tấm lòng của mình để quan tâm, lo lắng cho những người xung quanh còn nhiều vất vả, khó khăn.
Thương thân nghĩa là yêu thương chính bản thân chúng ta. Chúng ta luôn trân trọng, chăm lo đến bản thân rất nhiều và đó là điều tất yếu.
Cả câu tục ngữ: Thương người như thể thương thân mang đến cho chúng ta suy nghĩ rằng: chúng ta yêu thương, trân trọng, chăm sóc bản thân mình như thế nào thì hãy mở rộng tấm lòng của mình yêu thương những người xung quanh mình như thế đó.
- Yêu thương người khác đặc biệt là những người còn gặp nhiều khó khăn luôn là truyền thống đạo đức tốt đẹp của dân tộc Việt Nam chúng ta.



- Người sống trong xã hội, không ai sống lẻ loi, đơn độc được mà phải tập hợp thành đoàn thể, cộng đồng. Trong gia đình ta có mối quan hệ anh em, những người cùng huyết thống, cùng có những kỉ niệm vui buồn bên nhau. Họ chẳng khác nào như chân với tay trong cùng một cơ thể. Do đó khi có ai gặp hoạn nạn khó khăn, mọi người đâu nỡ quay mặt làm ngơ cho được, bởi “máu chảy ruột mềm”.
- Ai cũng mong muốn cuộc sống của mình được hạnh phúc, ấm no, đầy đủ, không cực khổ, nhưng không phải ai cũng đạt được như vậy. Có những người dù đã vô cùng cố gắng nhưng họ vẫn gặp phải hết khó khăn này đến khó khăn khác, ít khi đạt được điều mà mình mong muốn. Những lúc khó khăn mệt mỏi như vậy mà nhận được tình yêu thương, sự sẻ chia, giúp đỡ chân tình thì họ sẽ vơi đi bao nỗi ưu tư, phiền muộn và được tiếp thêm niềm tin và nghị lực để tiếp tục tiến về phía trước. Ngoài ra, khi ta giúp đỡ, cho đi tình yêu thương ta sẽ nhận được niềm vui, sự thanh thản cũng như cảm thấy tự hào với bản thân vì mình đã làm được những việc tốt, những điều có ích. Đó cũng là những việc làm nhân đạo để góp phần xây dựng một cuộc sống văn minh, tiến bộ và tươi đẹp, giàu tình nhân ái.
- Một xã hội sẽ trở nên đóng băng, cô độc và nhanh chóng tan rã nếu như không có hơi ấm của tình yêu thương Đặc biệt cuộc sống với bao bộn bề lo toan khi bình yên khi sóng gió ta luôn luôn cần đến sự quan tâm giúp đỡ của những người xung quanh. Cho nên khi ta biết cho đi tình yêu thì mới mong nhận được lại sự chia sẻ yêu thương từ người khác. Những kẻ ích kỉ vụ lợi chỉ biết sống vì mình thì mãi mãi sẽ sống cô độc và không bao giờ có được sự đồng cảm giúp đỡ khi gặp khó khăn trở ngại.
