### ISSUE TITLE
Bài 4: bài toán và thuật toán

### ISSUE THREAD

**Issue by thanhthao10A12** [thanhthao10A12/Lop-10A12-Nhom-09#6]

**Comment by TranQuocDuyTVND10A12** [comment]
Mai mốt rút kinh nghiệm có gì chào nhau ở đây nhà chứ dícuss thầy coi k đc đâu á

**Comment by thanhthao10A12** [comment]
nhớ vào phần projects trả lời câu hỏi nha, tui có chia câu hỏi ròi á

**Comment by thanhthao10A12** [comment]
nhớ vào phần projects trả lời câu hỏi nha, tui có chia ròi á :}

**Comment by duchuypn10a12** [comment]
Thuật toán viết theo kiểu nào á mn
Viết code á hả

**Comment by duchuypn10a12** [comment]
> > Tui thuyết trình nha có gì tui tìm thêm ý cho mọi người
> 
> ko có thuyết trình nha con

dạ vâng ạ

**Comment by thanhthao10A12** [comment]
@TranQuocDuyTVND10A12 
Duy ơi tranh thủ trả lời câu hỏi nha để tui tổng hợp lại nữa :}}

**Comment by thanhthao10A12** [comment]
ạ lộ cạ nhà ợi cọ ại thệm gị vạo bại lạm thị thệm vạo đí nhạ!!!
