### ISSUE TITLE
Câu hỏi tìm hiểu bài 5, bài 6

### ISSUE THREAD

**Issue by thanhthao10A12** [thanhthao10A12/Lop-10A12-Nhom-09#7]

**Comment by thanhthao10A12** [comment]
https://bom.to/DRxkNo 
câu hỏi tìm hiểu bài 5, 6 nè mấy pạng, nhớ làm nka!!!

**Comment by duchuypn10a12** [comment]
> https://bom.to/DRxkNo câu hỏi tìm hiểu bài 5, 6 nè mấy pạng, nhớ làm nka!!!

ok nha

**Comment by duchuypn10a12** [comment]
@thanhthao10A12 câu hỏi ở đâu á

**Comment by thanhthao10A12** [comment]
file ở trên đó Huy :}}

**Comment by duchuypn10a12** [comment]
> file ở trên đó Huy :}}

Thế á cảm ơn nhưng mà file lỗi hay sao á

**Comment by thanhthao10A12** [comment]
[Câu hỏi tìm hiểu tuần 9.docx](https://github.com/thanhthao10A12/Lop-10A12-Nhom-09/files/7465386/Cau.h.i.tim.hi.u.tu.n.9.docx)

**Comment by duchuypn10a12** [comment]
> [Câu hỏi tìm hiểu tuần 9.docx](https://github.com/thanhthao10A12/Lop-10A12-Nhom-09/files/7465386/Cau.h.i.tim.hi.u.tu.n.9.docx)

cảm ơn nhiều

**Comment by duchuypn10a12** [comment]
> [Câu hỏi tìm hiểu tuần 9.docx](https://github.com/thanhthao10A12/Lop-10A12-Nhom-09/files/7465386/Cau.h.i.tim.hi.u.tu.n.9.docx)

Đổi câu đc kh á Thảo, chứ câu 4 t kh chắc làm đc kh á

**Comment by thanhthao10A12** [comment]
> > [Câu hỏi tìm hiểu tuần 9.docx](https://github.com/thanhthao10A12/Lop-10A12-Nhom-09/files/7465386/Cau.h.i.tim.hi.u.tu.n.9.docx)
> 
> Change câu đc kh á Thảo, chứ câu 4 t kh chắc làm đc kh á

câu 4 nó liên quan tới câu 3 á m, có gì thì m trao đổi thêm với Thuận nữa.

**Comment by thanhthao10A12** [comment]
m cứ làm đi gặp khó khăn gì thì mỗi đứa giúp nhau xíu, còn khum biếc nữa thì đi hỏi thầy "Hiền so đoẹp" :}}}

**Comment by thanhthao10A12** [comment]
z nhoa, nên cứ làm đy pặng :}}

**Comment by duchuypn10a12** [comment]
> z nhoa, nên cứ làm đy pặng :}}

okay

**Comment by LeQuangThuan10a12** [comment]
tuii vừa gửi bài lên á
