### ISSUE TITLE
Bài 7; 8

### ISSUE THREAD

**Issue by thanhthao10A12** [thanhthao10A12/Lop-10A12-Nhom-09#8]

**Comment by thanhthao10A12** [comment]
(\_/)
(•_•)
/ >🎁[Câu hỏi tìm hiểu Tuần 10 (1).docx](https://github.com/thanhthao10A12/Lop-10A12-Nhom-09/files/7511257/Cau.h.i.tim.hi.u.Tu.n.10.1.docx)
quà tặng cuộc sống ~~~

**Comment by duchuypn10a12** [comment]
> 🎁[Câu hỏi tìm hiểu Tuần 10 (1).docx](https://github.com/thanhthao10A12/Lop-10A12-Nhom-09/files/7511257/Cau.h.i.tim.hi.u.Tu.n.10.1.docx) quà tặng cột sống dành tặng các bạn ~~~ @duchuypn10a12 @LeQuangThuan10a12 @TranQuocDuyTVND10A12 nhớ làm đó nhe

ok nha
