### ISSUE TITLE
Bài 9; 10

### ISSUE THREAD

**Issue by thanhthao10A12** [thanhthao10A12/Lop-10A12-Nhom-09#9]

**Comment by thanhthao10A12** [comment]
[Câu hỏi tìm hiểu Tuần 11.docx](https://github.com/thanhthao10A12/Lop-10A12-Nhom-09/files/7546239/Cau.h.i.tim.hi.u.Tu.n.11.docx)
hú hu quà tặng siu toa khổng lồ tuần 11 nèk mụi người @duchuypn10a12 @LeQuangThuan10a12 @TranQuocDuyTVND10A12

**Comment by duchuypn10a12** [comment]
Hú hú oyeah

**Comment by duchuypn10a12** [comment]
Mn rep mình đi cho thầy thấy là mình có làm việc nhóm
